import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

import '../constants.dart';

class PrivacyPolicy extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: backgroundColor,
        centerTitle: true,
        title: Text('Privacy Policy'
        ),
      ),
        body: SingleChildScrollView(
            padding: EdgeInsets.all(10),
            child: Text('PRIVACY NOTICE \n Last Revision: Oct 20, 2021 \n\nThank you for choosing to be a part of our community at Cita(\"Company,\" \"we,\" \"us,\" or '
                '\"our\"). We are committed to protecting your personal information and your right to privacy. If you have '
                'any questions or concerns about this privacy notice or our practices with regard to your personal information, please contact '
                'us at citaappproject@gmail.com. \n\nThis privacy notice describes how we might use your information if you: '
                '\n\n\u2022 Download and use our mobile application \u2015 Cita \n\nIn this privacy notice, if we refer to:\n\n'
                '\u2022 \"App,\" we are referring to any application of ours that references or links to this policy, including any listed above \n'
                '\u2022 \"Services,\" we are referring to our App, and other related services, including any potential sales, marketing, or events. \n\n'
                'The purpose of this privacy notices is to explain to you in the clearest way possible what information we collect, how e use it, and what rights you have '
                'in relation to it. If there are any terms in this privacy notice that you do not agree with, please discontinue use of our Services immediately. \n\n'
                'Please read this privacy notice carefully, as it will help you to understand what we do with the information we collect. \n\n'
                '1. WHAT INFORMATION DO WE COLLECT? \n\n'
                'In Short: we collect personal information that you provide to us. \n\n'
                'We collect personal information that you voluntarily provide to us when you register on the App, express an interest in obtaining information about us or our products and Services, when you'
                ' participate in activities on the App or when you contact us. \n\n'
                'The personal information that we collect depends on the context of your interactions with us and the App, the choices you make and the products and features you use. '
                'The personal information we collect may include the following: \n\n'
                'Personal Information Provided by You. We collect names; date of birth; gender; email addresses; usernames; passwords; and other similar information. \n\n'
                'All personal information that you provide to us must be true, complete and accurate, and you must notify us of any changes to such personal information. \n\n'
                'Information Automatically Collected \n\n'
                'In Short: Some information \u2015 such as your Internet Protocol (IP) address and/or browser and device characteristics \u2015 is collected automatically when you visit our App. \n\n'
                'We automatically collect certain information when you visit, use or navigate the App. This information does not reveal your specific identity(like your name or contact information '
                'but may include device and usage information, such as your IP address, browser and device characteristics, operating system, language preferences, referring URLs, device name, country, location, '
                'information about how and when you use our App and other technical information. This information is primarily needed to maintain the security and operation of our App, and for our internal analytics and '
                'reporting purposes. \n\n'
                'The information we collect includes: \n\n'
                '\u2022 Location Data. We collect location data such as information about your devices location, which can be either precise or imprecise. How much information we collect depends on the type and settings of the '
                'device you use to access the App. For example, we may use GPS and other technologies to collect geolocation data that tells us your current location (based on your IP address). You can opt out of allowing us to collect '
                'this information either by refusing access to the information or by disabling your Location setting on your device. Note however, if you choose to opt out, you may not be able to use certain aspects of Services. \n\n'
                'Information collectd through our App \n\n'
                'In Short: we collect information regarding your geolocation, mobile device, push notifications, when you use our App. \n\n'
                'The following information is collected when using our App: \n\n'
                '\u2022 Geolocation information. We may request access or permission to and track location-based information from your mobile device, either continuously or while you are using our App, to provide certain location-based services. '
                'If you wish to change our access or permissions, you may do so in your device\'s settings. \n'
                '\u2022 Mobile Device Access. We may request access or permission to to certain features from your mobile device, including your mobile device\'s storage, camera, and other features. If you wish to change our access or permissions, '
                'may do in your device\'s settings. \n'
                '\u2022 Push Notifications. We may request to send you push notifications regarding your account or certain features of the App. If you wish to opt-out from receiving these types of communications, you may turn them off in your device\'s settings. \n\n'
                'This information is primarily needed to maintain the security and operation of our App, for troubleshooting and for our internal analytics and reporting purposes. \n\n'
                '2. HOW DO WE USE YOUR INFORMATION? \n\n'
                'In Short: We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent. \n\n'
                'We use the information we collect or receive: \n\n'
                '\u2022 To facilitate account creation and logon process. If you choose to link your account with us to a third-party account (such as your Google or Facebook account), we use the information you allowed us to collect from those third parties to facilitate '
                'account creation and logon process for the performance of the contract. \n'
                '\u2022 Request feedback. We may use your information to request feedback and to contact you about your use of our App. \n'
                '\u2022 To enable user-to-user communications. We may use your information in order to enable user-to-user communications with each user\'s consent. \n'
                '\u2022 To manage user accounts. We may use your information for the purposes of managing our account and keeping it in working order. \n\n'
                '3. WILL YOUR INFORMATION BE SHARED WITH ANYONE? \n\n'
                'In Short: We only share information with your consent, to comply with laws, to provide you with services, to protect your rights, or to fulfill business obligations. \n\n'
                'We may process or share your data that we hold based on the following legal basis: \n\n'
                '\u2022 Consent: We may process your data if you have given us specific consent to use your personal information for a specific purpose. \n'
                '\u2022 Legitimate Interests: We may process your data when it is reasonably necessary to achieve our legitimate business interests. \n'
                '\u2022 Performance of a Contract: Where we have entered into a contract with you, we may process your information to fulfill the terms of our contract. \n'
                '\u2022 Legal Obligations: We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, '
                'court order or a subpoena (including in response to a public authorities to meet national security or law enforcement requirements). \n'
                '\u2022 Vital Interests: We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our polices, suspected fraud, situations involving potential threats to the safety of any person and '
                'illegal activities, or as evidence in litigation in which we are involved. \n'
                'More specifically, we may need to process your data or share your personal information in the following situations: \n\n'
                '\u2022 Business Transfers. We may share or transfer your information in connection with, or during negotiations of , any merger, sale of company asses, financing, or acquisition of all or a portion of our business to another company. \n'
                '\u2022 Google Maps Platform APIs. We may share your information with certain Google Maps Platform APIs (e.g., Google Maps API, Place API). To find out more about Google\'s Privacy Policy, please refer to this URL: https://policies.google.com/privacy. We obtain and store '
                'on your device (\'cache\') your location. You may revoke your consent anytime by contacting us at the contact details provided at the end of this document. \n\n'
                '4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES? \n\n'
                'In Short: We may use cookies and other tracking technologies to collect and store your information. \n\n'
                'We may use your cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Notice. \n\n'
                '5. HOW LONG DO WE KEEP YOUR INFORMATION? \n\n'
                'In Short: We keep your information for as long as necessary to fulfill the purposes outlined in this privacy notice unless otherwise required by law. \n\n'
                'We only will keep your personal information for as long as it is necessary for the purposes set out in this privacy notice, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements).'
                'No purpose in this notice will require us keeping your personal information for longer than the period of time in which users have an account with us. \n\n'
                'When we have no ongoing legitimate business need to process your personal will either delete or anonymize such information, or, if this is not a possible (for example, because your personal information has been stored in backup archives), then we will securely store '
                'your personal information and isolate it from any further processing until deletion is possible. \n\n'
                '6. HOW DO WE KEEP YOUR INFORMATION SAFE? \n\n'
                'In Short: we aim to protect your personal information through a system of organizational and technical security measures. \n\n'
                'We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, despite our safeguards and efforts to secure your information, no electronic transmission over the internet '
                'or information storage technology can be guaranteed to be 100% secure, so we cannot promise or guarantee that hackers, cybercriminals or other unauthorized third parties will not be able to defeat our security, and improperly collect, access, steal, or modify your information. Although we will do our best '
                'to protect your personal information, transmission of personal information to and from our App is at your own risk. You should only access the App within a secure environment. \n\n'
                '7.WHAT ARE YOUR PRIVACY RIGHTS? \n\n'
                'If you have questions or comments about your privacy rights, you may email us at citaappproject@gmail.com \n\n'
                'Account Information \n\n'
                'If you would at any time like to review or change the information in your account or terminate your account, you can: \n\n'
                '\u2022 Log into your account settings and update your user account. \n\n'
                'Upon your request to terminate your account, we will deactivate your delete your account and information from our active databases. However, we may retain some information in our files to prevent '
                'fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use and/or comply with applicable legal requirements. \n\n'
                '8. CONTROLS FOR DO-NOT-TRACK FEATURES \n\n'
                'Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (\"DNT\") feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. '
                'At this stage, no uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. '
                'If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this privacy notice. \n\n'
                '9. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS? \n\n'
                'In Short: Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information. \n\n'
                'California Civil Code Section 1798.83, also known as the \"Shine The Light\" law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties '
                'for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using '
                'the contact information provided below. \n\n'
                'If you are under 18 years of age, reside in California, and have a registered account with the App, you have the right to request removal of unwanted data that you publicly post on the App. To request removal of such data, please contact us using the contact information provided below, and '
                'and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the App, but please be aware that the data may not be completely or comprehensively removed from all our systems (e.g. backups, etc.). \n\n'
                'CCPA Privacy Notice \n\n'
                'The California Code of Regulations defines a \"resident\" as: \n\n'
                '\u2022(1) every individual who is in the State of California for other than a temporary or transitory purpose and \n'
                '\u2022(2) every individual who is domiciled in the State of California who is outside the State of California for a temporary or transitory purpose \n\n'
                'All other individuals are defined as \"non-residents.\" \n\n'
                'If this definition of \"resident\" applies to you, we must adhere to certain rights and obligations regarding your personal information. \n\n'
                'What categories of personal information do we collect? \n\n'
                'We have collected the following categories of personal information in the past (12) months: \n'
                '\u2022 Personal Information categories listed in the California Customer Records statute. These include: Name, contact information, education, employment, employment history and financial information. \n\n'
                '\u2022 Protected classification characteristics under California or federal law. This includes Gender and date of birth. \n'
                '\u2022 Geolocation data. This includes Device location \n\n'
                'How do we use and share your personal information? \n\n'
                'More information about our data collection and sharing practices can be found in this privacy notice. \n\n'
                'You may contact us by email at citaappproject@gmail.com, or by referring to the contact details at the bottom of this document. \n\n'
                'If you are using an authorized agent to exercise your right to opt-out we may deny a request if the authorized agent does not submit proof that they have been validly authorized to act on your behalf. \n\n'
                'Will your information be shared with anyone else? \n\n'
                'We may disclose your personal information with our service providers pursuant to a written contract between us and each service provider. Each service provider is a for-profit entity that processes the information o our behalf. \n\n'
                'We may use your personal information for our own business purposes, such as for undertaking internal research for technological development and demonstration. This is not considered to be \"selling\" of your personal data. \n\n'
                'Cita has not disclosed or sold any personal information to third parties for a business or commercial purpose in the preceding 12 months. Cita will not sell personal information in the future belonging to website visitors, users and other consumers. \n\n'
                'Your rights with respect to your personal data \n\n'
                'Right to request deletion of the data - Request to delete: \n\n'
                'You can ask for the deletion of your personal information. If you ask us to delete your personal information, we will respect your request and delete your personal information, subject to certain exceptions provided by law, such as (but not limited to) the exercise by another consumer of his or her right to free speech, '
                'our compliance requirements resulting from a legal obligation or any processing that may be required to protect against illegal activities. \n\n'
                'Right to be informed - Request to know: \n\n'
                'Depending on the circumstances, you have the right to know: \n\n'
                '\u2022 whether we collect and use your personal information; \n'
                '\u2022 the categories of personal information that we collect; \n'
                '\u2022 the purposes for which the collected personal information is used; \n'
                '\u2022 whether we sell your personal information to third parties; \n'
                '\u2022 the categories of third parties to whom the personal information was sold or disclosed for a business purpose; and \n'
                '\u2022 the business or commercial purpose for collecting or selling personal information \n\n'
                'In accordance with applicable law, we are not obligated to provide or delete consumer information that is de-identified in response to a consumer request or to re-identify individual data to verify a consumer request. \n\n'
                'Right to Non-Discrimination for the Exercise of a Consumer\'s Privacy Rights \n\n'
                'We will not discriminate against you if you exercise your privacy rights. \n\n'
                'Verification process \n\n'
                'Upon receiving your request, we will need to verify your identity to determine you are the same person about whom we have the information in your system. These verification efforts require us to ask you to provide information so that we can match it with information '
                'you have previously provided us. For instance, depending on the type of request you submit, we may ask you to provide certain information so that we can match the information you provide with the information we already have on file, or we may contact you through a communication method (e.g. phone or email) that you have previously '
                'provided to us. We may also use other verification methods as the circumstances dictate. \n\n'
                'We will only use personal information provided in your request to verify your identity or authority to make the request. To the extent possible, we will avoid requesting additional information from you for the purposes of verification. If, however, we cannot verify your identity from the information already maintained by us, we may request that you provide '
                'additional information for the purposes of verifying your identity, and for security or fraud-prevention purposes. We will delete such additionally provided information as soon as we finish verifying you. \n\n'
                'Other privacy rights \n\n'
                '\u2022 you may object to the processing of your personal data \n'
                '\u2022 you may request correction of your personal data if it is incorrect or no longer relevant, or ask to restrict the processing of the data \n'
                '\u2022 you can designate an authorized agent to make a request under the CCPA on your behalf. We may deny a request from an authorized agent that does not submit proof that they have been validly authorized to act on your behalf in accordance with the CCPA. \n'
                '\u2022 you may request to opt-out from future selling of your personal information to third parties. Upon receiving a request to opt-out, we will act upon the request as soon as feasibly possible, but no later than 15 days from the date fo the request submission. \n\n'
                'To exercise these rights, you can contact us by email at citaappproject@gmail.com, or by referring to the contact details at the bottom of this document. If you have a complaint about how we handle your data, we would like to hear from you. \n\n'
                '10. DO WE MAKE UPDATES TO THIS NOTICE? \n\n'
                'In Short: Yes, we will update this notice as necessary to stay compliant with relevant laws. \n\n'
                'We may update this privacy notice from time to time. The updated version will be indicated by an updated \"Revised\" date and the updated version will be effective as soon as accessible. If we make material changes to this privacy notice, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We '
                'encourage you to review this privacy notice frequently to be informed of how we are protecting your information. \n\n'
                '11. HOW CAN YOU CONTACT US ABOUT THIS NOTICE? \n\n'
                'If you have questions or comments about this notice, you may email us at citaappproject@gmail.com or by post to: \n\n'
                'Cita \n'
                '201 Presidents\' Cir \n'
                'Salt Lake City, UT 84112 \n'
                'United States \n\n'
                '12. HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU? \n\n'
                'Based on the applicable laws of your contry, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please submit a request by emailing citaappproject@gmail.com.'
            )
        ),
    );
  }
}
